name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          git config user.name "Sergei Lutov"
          git config user.email "doublemakers@gmail.com"
          npm version ${{ github.event.inputs.version }}
          npm run build
          npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}