name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: |
          git config --global user.name "Sergei Lutov"
          git config --global user.email "doublemakers@gmail.com"
          npm version ${{ github.event.inputs.version }}
      - run: npm run build
      - run: npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.npm_token }}